### ISSUE TITLE
Submitting app conversation path is unclear

### ISSUE THREAD

**Issue by Noah-Huppert** [kscout/chat-bot-api#86]
During the demo I was confused to the conversation path I should follow to get information about submitting an app.

Try to make it clearer.

It wasn't immediately clear that "Getting started" would show me the information I wanted. Maybe make it clear _what_ they are getting started with.

**Comment by VaishnaviHire** [comment]
Fixed the bug. Chatbot can answer `how to submit an app` , `how to create an app`
