### ISSUE TITLE
Cannot search apps

### ISSUE THREAD

**Issue by Noah-Huppert** [kscout/chat-bot-api#95]
![2019-07-24-17-52-22](https://user-images.githubusercontent.com/3323504/61831439-d9afee80-ae3b-11e9-977d-15fc39a9d753.png)
![2019-07-24-17-52-33](https://user-images.githubusercontent.com/3323504/61831446-dc124880-ae3b-11e9-816e-40c26cee32b8.png)

**Comment by Noah-Huppert** [comment]
I couldn't get any results for 

- `serverless`: Got definition of serverless
- `nodejs`, `apps`, `python`, `node`, `node apps`: Got hmm, I don't understand...

For some reason `webhook` worked.

**Comment by VaishnaviHire** [comment]
Yes, apps data was missing for few minutes as I was debuging the `/newapps` endpoint. It can be accessed now.
![search](https://user-images.githubusercontent.com/17230536/61832009-b6863e80-ae3d-11e9-9db3-a08a9e683c01.png)
